#importing champions' definitions

from packages.champions.aatrox import Aatrox
from packages.champions.ahri import Ahri
from packages.champions.akali import Akali
from packages.champions.alistar import Alistar
from packages.champions.amumu import Amumu
from packages.champions.anivia import Anivia
from packages.champions.annie import Annie
from packages.champions.ashe import Ashe
from packages.champions.blitzcrank import Blitzcrank
from packages.champions.brand import Brand
from packages.champions.caitlyn import Caitlyn
from packages.champions.cassiopeia import Cassiopeia
from packages.champions.cho_gath import Cho_Gath
from packages.champions.corki import Corki
from packages.champions.darius import Darius
from packages.champions.diana import Diana
from packages.champions.dr_mundo import Dr_Mundo
from packages.champions.draven import Draven
from packages.champions.elise import Elise
from packages.champions.evelynn import Evelynn
from packages.champions.ezreal import Ezreal
from packages.champions.fiddlesticks import Fiddlesticks
from packages.champions.fiora import Fiora
from packages.champions.fizz import Fizz
from packages.champions.galio import Galio
from packages.champions.gangplank import Gangplank
from packages.champions.garen import Garen
from packages.champions.gragas import Gragas
from packages.champions.graves import Graves
from packages.champions.hecarim import Hecarim
from packages.champions.heimerdinger import Heimerdinger
from packages.champions.irelia import Irelia
from packages.champions.janna import Janna
from packages.champions.jarvan_iv import Jarvan_IV
from packages.champions.jax import Jax
from packages.champions.jayce import Jayce
from packages.champions.jinx import Jinx
from packages.champions.karma import Karma
from packages.champions.karthus import Karthus
from packages.champions.kassadin import Kassadin
from packages.champions.katarina import Katarina
from packages.champions.kayle import Kayle
from packages.champions.kennen import Kennen
from packages.champions.kha_zix import Kha_Zix
from packages.champions.kog_maw import Kog_Maw
from packages.champions.leblanc import LeBlanc
from packages.champions.lee_sin import Lee_Sin
from packages.champions.leona import Leona
from packages.champions.lissandra import Lissandra
from packages.champions.lucian import Lucian
from packages.champions.lulu import Lulu
from packages.champions.lux import Lux
from packages.champions.malphite import Malphite
from packages.champions.malzahar import Malzahar
from packages.champions.maokai import Maokai
from packages.champions.master_yi import Master_Yi
from packages.champions.miss_fortune import Miss_Fortune
from packages.champions.mordekaiser import Mordekaiser
from packages.champions.morgana import Morgana
from packages.champions.nami import Nami
from packages.champions.nasus import Nasus
from packages.champions.nautilus import Nautilus
from packages.champions.nidalee import Nidalee
from packages.champions.nocturne import Nocturne
from packages.champions.nunu import Nunu
from packages.champions.olaf import Olaf
from packages.champions.orianna import Orianna
from packages.champions.pantheon import Pantheon
from packages.champions.poppy import Poppy
from packages.champions.quinn import Quinn
from packages.champions.rammus import Rammus
from packages.champions.renekton import Renekton
from packages.champions.rengar import Rengar
from packages.champions.riven import Riven
from packages.champions.rumble import Rumble
from packages.champions.ryze import Ryze
from packages.champions.sejuani import Sejuani
from packages.champions.shaco import Shaco
from packages.champions.shen import Shen
from packages.champions.shyvana import Shyvana
from packages.champions.singed import Singed
from packages.champions.sion import Sion
from packages.champions.sivir import Sivir
from packages.champions.skarner import Skarner
from packages.champions.sona import Sona
from packages.champions.soraka import Soraka
from packages.champions.swain import Swain
from packages.champions.syndra import Syndra
from packages.champions.talon import Talon
from packages.champions.taric import Taric
from packages.champions.teemo import Teemo
from packages.champions.thresh import Thresh
from packages.champions.tristana import Tristana
from packages.champions.trundle import Trundle
from packages.champions.tryndamere import Tryndamere
from packages.champions.twisted_fate import Twisted_Fate
from packages.champions.twitch import Twitch
from packages.champions.udyr import Udyr
from packages.champions.urgot import Urgot
from packages.champions.varus import Varus
from packages.champions.vayne import Vayne
from packages.champions.veigar import Veigar
from packages.champions.vi import Vi
from packages.champions.viktor import Viktor
from packages.champions.vladimir import Vladimir
from packages.champions.volibear import Volibear
from packages.champions.warwick import Warwick
from packages.champions.wukong import Wukong
from packages.champions.xerath import Xerath
from packages.champions.xin_zhao import Xin_Zhao
from packages.champions.yorick import Yorick
from packages.champions.zac import Zac
from packages.champions.zed import Zed
from packages.champions.ziggs import Ziggs
from packages.champions.zilean import Zilean
from packages.champions.zyra import Zyra